services:
  - type: web
    name: sudharsan-portfolio-backend # Choose a unique name for your backend service
    runtime: python3
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10 # Or your preferred Python version

  - type: static
    name: sudharsan-portfolio-frontend # Choose a unique name for your frontend service
    buildCommand: npm install && npm run build
    staticDir: public
