services:
  - type: web
    name: sudharsan-portfolio-backend
    runtime: python3
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  - type: static
    name: sudharsan-portfolio-frontend
    buildCommand: npm install && npm run build
    staticDir: public
    routes:
      - src: /*
        dest: /
